### ISSUE TITLE
Not functional on Ubuntu 14.04 with avconv instead of ffmpeg

### ISSUE THREAD

**Issue by pete-otaqui** [ListenerApproved/node-ffprobe#11]
See this issue on AskUbuntu:

http://askubuntu.com/questions/432542/is-ffmpeg-missing-from-the-official-repositories-in-14-04

Essentially `ffmpeg` was removed from Ubuntu a while ago in favour of a fork called `avconv`.

I've installed the `avconv` package which, apparently as of 14.04, no longer provides an `ffmpeg` executable of any kind, so mod-ffprobe fails like so:

```
events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: spawn ENOENT
    at errnoException (child_process.js:988:11)
    at Process.ChildProcess._handle.onexit (child_process.js:779:34)
```

I created a symlink from `/usr/local/bin/ffmpeg` to the `/usr/bin/avconv` that the package installed, but still got the same error.

**Comment by kriptolix** [comment]
You can chage the line 84 of lib ffprobe.js from 'ffprobe' to 'avprobe', it works from me. Maybe to make a test to detect how of them is installed could be instersting.
