### ISSUE TITLE
wrong mp3 duration

### ISSUE THREAD

**Issue by chideat** [ListenerApproved/node-ffprobe#13]
As if the duration of mp3 is 2 or 3 seconds larger than the real.

**Comment by njoyard** [comment]
Uh... You realize I have no idea what you're talking about here ?
Please give more info about the problem.

**Comment by chinat** [comment]
Sorry.
The duration of mp3 got with `node-ffprobe` is not correct. It's about 2 to 3 seconds larger than the real duration.

**Comment by njoyard** [comment]
node-ffprobe is a wrapper around ffprobe. We have no control over the results it gives. You should seek help at http://ffmpeg.org/contact.html, I guess.

**Comment by chinat** [comment]
Thanks
