### ISSUE TITLE
New ffmpeg

### ISSUE THREAD

**Issue by aalku** [ListenerApproved/node-ffprobe#17]
New ffmpeg change tool names and more. ffprobe is now called avprobe and need the arguments "-of old" to use the output format node-ffprobe expects.

**Comment by njoyard** [comment]
avprobe is not part of a new ffmpeg. It's part of avconv, which is/was shipped by default by debian/ubuntu.

**Comment by aalku** [comment]
You are right, sorry. I just read it somewhere else. It seems it is a fork that tried to take the place of the original and made it into debian repo. Some versions impersonated the original ffmpeg and said the tool names was going to change and some newer version removed the ffmpeg file names breaking compatibility.  Ugly things. Thank you and sorry.

**Comment by njoyard** [comment]
No need to be sorry!
Actually I think debian announced they would go back to ffmpeg. If you need the _real_ ffmpeg, in the mean time, you can install it from the ffmpeg website.
