### ISSUE TITLE
set path to ffprobe binary file?

### ISSUE THREAD

**Issue by pietrop** [ListenerApproved/node-ffprobe#18]
In node [ffmpeg-fluent you can set the path to the ffmpeg binary file](https://github.com/fluent-ffmpeg/node-fluent-ffmpeg#setting-binary-paths-manually). Which is handy if you need to package it or deploy it somewhere where ffmpeg might not be installed on the system. 

I was wondering if there's a way to do that with `node-ffprobe` ?

**Comment by btipling** [comment]
The [README](https://github.com/ListenerApproved/node-ffprobe/blob/master/README.md#usage) mentions you can do this:

```javascript
ffprobe.FFPROBE_PATH = ffprobeInstaller.path;
```
> FFPROBE_PATH is useful if you embed the lib in your app.
