### ISSUE TITLE
NPM didn't have latest version.

### ISSUE THREAD

**Issue by vestayin** [ListenerApproved/node-ffprobe#21]
I tried to install this package via npm. It only have 1.2.2 version which didn't support to customize ffprobe path by probe.FFPROBE_PATH. In current git version that is 1.3 already have that. And 1.3 worked well for my case. Is that possible to publish this 1.3 version to npm so that it will easy for me to distribute my project to others rather than package 1.3 into my project? Thanks.

**Comment by vestayin** [comment]
Figured out an approach that node package.json support github project directly as well as npm package. Just use below under dependencies. 
 "node-ffprobe": "github:ListenerApproved/node-ffprobe"

**Comment by ScottyFillups** [comment]
@vestayin if you're interested, I've created my own ffprobe library which is actively maintained: https://www.npmjs.com/package/ffprobe-client
